/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KolekcjeIndexRouteImport } from './routes/kolekcje.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KolekcjeIndexRoute = KolekcjeIndexRouteImport.update({
  id: '/kolekcje/',
  path: '/kolekcje/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kolekcje/': typeof KolekcjeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kolekcje': typeof KolekcjeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kolekcje/': typeof KolekcjeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kolekcje/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kolekcje'
  id: '__root__' | '/' | '/kolekcje/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KolekcjeIndexRoute: typeof KolekcjeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolekcje/': {
      id: '/kolekcje/'
      path: '/kolekcje'
      fullPath: '/kolekcje/'
      preLoaderRoute: typeof KolekcjeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KolekcjeIndexRoute: KolekcjeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
